### ISSUE TITLE
Move database backup-related code somewhere else than createTables.js

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#107]
Same as https://github.com/anthill/pheromon/issues/32#issuecomment-141796042
createTables should only create tables. Other things should be done elsewhere, a new tool can glue these functions together elsewhere too.

For reference, this was introduced in https://github.com/anthill/6element/pull/79/files#diff-f9300e43444141fb3325dec3e7101de0R14
Sorry for not catching that earlier.

**Comment by SergeBredin** [comment]
@DavidBruant Does this issue refer to the current version of 6element or previous Pheromon which has been moved ?

**Comment by DavidBruant** [comment]
Current https://github.com/anthill/6element/blob/39077ed94acf7eb46b4144910535fa48e6f46d25/server/database/management/createTables.js#L14-L32

**Comment by SergeBredin** [comment]
Fine. We need to adapt it to 6element. Previously, dump process wasn't much necessary because open data files were used to reload the db. But it's not enough anymore, bin data from sensors will involve to save dumps with cron jobs.
So let's keep this issue opened.

**Comment by DavidBruant** [comment]
Working on it.

**Comment by DavidBruant** [comment]
Requirements:
* Ability to create backups regularly (daily basis?)
* Ability to create backups at a button push
* Ability to restore a backup at a button push
* Hopefully, ability to download a dump from the server, load it in a local machine to be back in the same data configuration for easier debugging (perf/correctness)

**Comment by DavidBruant** [comment]
Keep the backup concerns outside of the application docker containers. The host machine can access the docker containers via `docker exec`. Perhaps do a docker service specifically for this purpose (with backup directory/volume specifically for that purpose). From the host machine, we can then `docker exec` this service to get the dump in stdin and forward it to any file or the network as in :
`docker exec 6element_backup_1 bin/backup > /path/to/backups/6element-latest.bak`. This can be triggered in a cron job in the host machine. This can also be launched from command line anytime.

This service can have a directory (read-only) volume for backups when need to restore. When one wants to restore a backup, it'd do:
```
cp backup-to-restore.bak /path/to/backup-service-volume/backup.bak # or symlink
docker exec -ti 6element_backup_1 bin/restore ./backup.bak # -ti for confirmation input
```
