### ISSUE TITLE
gulp watch-client takes ~8sec to rebuild

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#134]
With watchify, it'd take ~1sec.
I haven't been able to make watchify work with gulp. To be later attempted.
Another option is to stop bundling all at once and instead have a couple of bundles. One common to all pages, and others for specific pages to be lazy-loaded.

**Comment by DavidBruant** [comment]
Thanks @SergeBredin for the assignation :-p
Tempted to ditch gulp and do as in https://twitter.com/oncletom/status/671752711579287553
More infos : http://naholyr.fr/2015/11/ecrire-des-scripts-npm-multi-plateforme/

**Comment by vallettea** [comment]
I'm more and more thinking of removing docker for js dev. If we keep docker for db only and keep them always up and keep thé usual js dev protocol it could be luch faster

**Comment by DavidBruant** [comment]
> I'm more and more thinking of removing docker for js dev. If we keep docker for db only and keep them always up and keep thé usual js dev protocol it could be luch faster

@iOiurson told me yesterday indeed. Complicated multi-faceted topic. I'll be here next week, let's talk about that then, weigh pros and cons.

**Comment by DavidBruant** [comment]
Should be fixed by #145
