### ISSUE TITLE
Optimize init db (sql point of view)

### ISSUE THREAD

**Issue by vallettea** [anthill/6element#149]
It currently takes 15 minutes to load the data in the db.
I think it is because of:
- bad parameters of postgres
- index being present before insertion

**Comment by vallettea** [comment]
Removing the geo index before insertion doesn't accelerate the process.

**Comment by vallettea** [comment]
I wanted to change the postgres parameter but it unclear where this can be made since the postgres.conf file is rewritten when we run the container:

```
alter system set fsync='off';
alter system set synchronous_commit='off';
alter system set full_page_writes='off';
alter system set bgwriter_lru_maxpages=0;
alter system set wal_level='minimal';
alter system set archive_mode='off';
alter system set work_mem='64MB';
alter system set checkpoint_segments=32;
alter system set max_wal_senders=0;
alter system set maintenance_work_mem='64MB';
alter system set shared_buffers='128MB';
```

I see this later.

**Comment by vallettea** [comment]
I think the fastest way would be to make node generate a sql file and then use a `COPY` statement

**Comment by SergeBredin** [comment]
Guess was a docker issue.
