### ISSUE TITLE
Create URLs for 6element

### ISSUE THREAD

**Issue by vallettea** [anthill/6element#150]
There are many advantages in customising urls:

- for google analytics (we could know who looks at which recycling center)
- for referencing (we could have people landing on the page of the opening time of a place)
- for favorites (it can enable easily to have people only loading a specific page)
- for developing (when working on a specific vue, just reload)

**Comment by vallettea** [comment]
@DavidBruant uses [page](https://www.npmjs.com/package/page) to manage this in MWI: https://github.com/MyWebIntelligence/MyWebIntelligence/blob/master/client/index.js

**Comment by vallettea** [comment]
Here is draft of the url schema:

Here are some query parameters (QP):

- `loc=32.4,45.08` is the center of of the map
- `keywords=wood,metal` the things that somebody want to throw
- `zoomlevel=3` the map zoom level
- `filters=` to filter some sources


- `/` should show the search window only if `loc`and `keywords` are not set
- `/list` list view (mobile version)
- `/map` map view (mobile version)
- `/placeId/affluence` should show a place info with the affluence toggle
- `/placeId/availability` should show a place info with the affluence toggle

**Comment by SergeBredin** [comment]
Should we add a verbose routing for recycling center  (http://6element.fr/decheterie-bordeaux-surcouf?loc= <http://6element.fr/decheterie-bordeaux-surcouf?loc=>….) ?

**Comment by vallettea** [comment]
from @SergeBredin comment we should add:

- `/placeName/affluence`
`/placeName/availability`

**Comment by vallettea** [comment]
The situation is quite brain fucked due to server side rendering.
For example, if in front I add:

```
page("/place/:placeId", function (context){
    var placeId = Number(context.params.placeId);
    // props.detailedObjectId = placeId;
    ReactDOM.render( 
        React.createElement(Layout, props), document.getElementById('reactHere')
    );
});
```
we have the correct behaviour if the user comes to this page coming from the usual way (a search, a click). But things get complicated when the user just pastes the url with `/place/59904`.

The backend must know this route so I added:
```
app.get('/place/:placeId/', function(req, res){
    // Create a fresh document every time
    makeDocument(indexHTMLStr).then(function(result){
        var doc = result.document;
        var dispose = result.dispose;

        var placeId = Number(req.params.placeId);
        places.getPlaceById(placeId)
        .then(function(data){
            
            layoutData.detailedObject = data;

            // Material-ui needs to change the global.navigator.userAgent property
            // (just during the React  rendering)
            // Waiting for Material team to fix it 
            //https://github.com/callemall/material-ui/pull/2007#issuecomment-155414926
            global.navigator = {'userAgent': req.headers['user-agent']};
            renderDocumentWithData(doc, layoutData, Layout);
            global.navigator = undefined;

            res.send( jsdom.serializeDocument(doc) );
            dispose();
        })
        .catch(function(error){
            res.status(500).send('Couldn\'t get bins from database');
            console.log('error in GET /bins/' + pheromonId, error);
        });
    })
    .catch(function(err){ console.error('/place/:placeId', err, err.stack); }); 
});
```

to the server. As we see we need to query the db to fetch the place info and add this data to the `layoutData`.

However, in front, the `layoutData`is regenerated due to the require and we lose everything.

**Comment by vallettea** [comment]
I followed @DavidBruant trick with:
```
var initDataElement = document.querySelector('script#init-data');
```

**Comment by SergeBredin** [comment]
you kept bins/pheromon logs in catch error

**Comment by vallettea** [comment]
I'm copy/pasting the slack discussion we had on the subject:


@davidbruant: what was the reason why we shouldn’t use react-router ?

davidbruant [1:02 PM] 
@ourson: see discussion with Alex above :wink:

davidbruant [1:10 PM] 
It's not really that we ​*shouldn't*​, but more that page is closer to the express way of doing routes. This helps keeping things in sync on both sides

davidbruant [1:37 PM] 
I guess if we can find a way to manage routes on both sides with react-router, I'm in (but last time I tried it wasn't that easy)

​[1:38] 
The biggest argument against being that routes and UI components are rather orthogonal concerns and I don't feel comfortable mixing them (but can be convinced otherwise)

ourson [2:10 PM] 
> Also, the page approach, due to its similarity with express opens the way to something very declarative where we'd list URL patterns and associate a ReactComponent (and a handful of (hopefully) pure functions) to get the correct web page both on the client and server side

​[2:10] 
i don’t understand why in this case (rendering UI components) we would need the server side part

ourson [2:20 PM] 
what if we define express to direct `/app/*` routes to React-router (that will handle subsequent routes to draw corresponding UI) ?

davidbruant [2:23 PM] 
> i don’t understand why in this case (rendering UI components) we would need the server side part

Server-side rendering is a must for performance esp on mobile (3-round-trip diagram)

​[2:26] 
> what if we define express to direct /app/* routes to React-router

Does this work? ( I have no idea)

​[2:27] 
The `<Router>` components really makes me uncomortable. It really isn't a UI component.

alexandre [2:28 PM] 
@davidbruant: if you look at the current PR: https://github.com/anthill/6element/pull/157

GitHub
Adding urls by vallettea · Pull Request #157 · anthill/6element · GitHub
6element - Optimising waste management in recycle centers.

​[2:29] 
i’m stuck at https://github.com/vallettea/6element/blob/master/src/views/layout.jsx#L163

GitHub
vallettea/6element
6element - Optimising waste management in recycle centers.

​[2:29] 
that triggers a rerender

davidbruant [2:30 PM] 
and so does setstate?

​[2:30] 
in loop ?

alexandre [2:30 PM] 
no i’m not clear

davidbruant [2:31 PM] 
I guess the larger problem here is that we're lacking a principled archtuecture like Redux

alexandre [2:31 PM] 
humm thats what @ourson said but we have to finish it for tomorrow

davidbruant [2:33 PM] 
(why tomorrow?) The launch can survive not having deep URLs, they can be easily added later, no?

alexandre [2:34 PM] 
yes but we have no detailed google analytics… but since it’s only one place… humm you’re right

davidbruant [2:35 PM] 
super short term, you can inspect the history stack in the client-side route (`page('/place', function(){...}`) to see if the route has not change enough. In which case, don't trigger a re-render

​[2:38] 
wait... apparently, there is no way to read the history? damned... well, in the client-side route page, you can save the url

ourson [2:56 PM] 
@davidbruant: if you’re uncomfortable with the `<Router>`, `<Route>`, `<Link>` components because they aren’t UI component, you must know that Redux uses a `<Provider>` component that isn’t a UI either

davidbruant [2:57 PM] 
Are we using it?

ourson [2:57 PM] 
yes

​[2:58] 
otherwise, no redux

davidbruant [2:59 PM] 
Ok, but only at top-level from what I can see

​[2:59] 
hmm... I guess it's the same for routes

​[2:59] 
ok, I don't know, no strong opinion, let's have this discussion next week or so

ourson [3:00 PM] 
yep, i understand all those top level components as links between the state and your UI

sergebredin [3:01 PM] 
@davidbruant and @ourson : I’m gonna spend time through page documentation this afternoon. If we find the correct use, it's maybe  the lightest and most efficient short-term solution

ourson [3:01 PM] 
with redux-router, you can store your current route within the state

​[3:01] 
@sergebredin: i agree

davidbruant [3:28 PM] 
Totally unrelated, but on MyWI, I'm generated random ids (instead of SERIAL) in the database and it's easy and works perfectly.

sergebredin [4:53 PM] 
@David j’essaye de bien comprendre notre problème. Si on n’avait pas de server-side rendering, il suffirait d’ouvrir les routes côté serveur et de mettre à jour l’url à chaque modification du state côté client (avec history.pushState). Je me trompe ?

davidbruant [5:01 PM] 
Nos contraintes, c'est :
* Avoir des URLs
* Avoir la bonne UI en mode "single-page app" (donc, +/- déclencher un rendu quand l'URL change côté client)
* Avoir la bonne UI (avec des bonnes perfs, donc server-side rendering) quand qqun a bookmarké une URL

​[5:02] 
@sergebredin: ouais, mais le problème, c'est qu'on rendrait un <body> vide, donc pas génial au niveau des perfs

​[5:03] 
(enfin, non, tu ne te trompes pas)

​[5:04] 
pardon, je recommence :
ouais, mais le problème, c'est que une fois que la personne est sur une URL générée côté client, si la personne refresh (F5), alors depuis le serveur sans SSR on rendrait un <body> vide, donc pas génial au niveau des perfs

​[5:05] 
La contrainte finale, c'est de l'ingéniérie logicielle : on veut que ça soit facile de faire un changement d'UI. React aide bien (si le même composant est utilisé des deux côté, normallement, on change une fois, on déploie et les 2 côtés sont modifiés dans le même mouvement)

sergebredin [5:06 PM] 
En fait j’en suis arrivé à la conclusion qu’en:

​[5:06] 
1) ouvrant les routes côté serveur

​[5:07] 
2) le server rendering

​[5:07] 
3) Pages côté front, uniquement en amont de React (juste dans main.js)

​[5:08] 
4) un Windows.history.pushState(nouvel url) associé à chaque setState de react

​[5:08] 
on serait bon non ?

davidbruant [5:09 PM] 
plus ou moins. Le problème, c'est quand les gens cliquent sur des liens, utilisent les boutons back/forward du navigateur, etc, on ne veut pas recharger toute la page

​[5:09] 
La lib page.js et react-router jouent le rôle de capturer ces trucs et déclencher le bon re-rendu

​[5:10] 
(je suis sûr pour page.js, un peu moins pour react-router parce que je connais pas assez)

​[5:11] 
Mais dans l'esprit, c'est ça. Y'a juste le 4) qui est à changer un peu

​[5:16] 
ah attends, je crois que j'ai mal compris

sergebredin [5:16 PM] 
De ce que j’ai lu de Page, c’est vraiment un router et uniquement un router. Donc si tu veux l’utiliser partout, chaque setState de react devrait être remplacé par Page(ur_composé_des propriétés_du_state). Du coup utilisation peut-etre sous optimale de react non ?

davidbruant [5:16 PM] 
Tu voulais dire quoi par "3) Pages côté front" ?

​[5:16] 
Tu parlais de la lib page.js ?

sergebredin [5:16 PM] 
oui

davidbruant [5:17 PM] 
ah oui, donc c'est bon

​[5:18] 
(enfin, ça va déclencher un re-rendu quand même, non ?)

​[5:18] 
nan, vazy, m'écoute pas. Je pense que c'est bon. Ca dépend de comment tu fais la partie "un pushState associé à chaque setState"

sergebredin [5:19 PM] 
Ouais ca re-render pas

davidbruant [5:20 PM] 
Et dans le futur, on passera par des actions redux qui feront les appels à page() et normallement avec des bons shouldComponentUpdate, ça devrait se re-render que quand il faut

sergebredin [5:22 PM] 
Ok ça me rassure. En fait, on a déjà cette architecture, ça ne marche pas bien, mais maintenant on sait qu’y a plus qu’à débuguer.

​[5:23] 
On se tape des bugs de l’an 2000, on est dans la 3e dimension là

davidbruant [5:24 PM] 
ahahaah :simple_smile:

ourson [5:48 PM] 
IMVeryHO, react-router (and by extension redux-router) is correct enough

​[5:50] 
i’d suggest, if we’re going to use redux, to have a look into it, it might what we need and adapted to react architectures

**Comment by SergeBredin** [comment]
Done!
