### ISSUE TITLE
Consider using docker-to-docker communication with pheromon

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#156]
The server-side uses DNS resolution to communicate with pheromon which is... on the same machine
https://github.com/anthill/6element/blob/30919bbfd422343b33e7a7d84062600b7d443af4/server/searchFiles.js#L61

Perhaps we should consider that 6element docker file should start services from pheromon's docker-compose file. On the other hand, the current architecture allows for pheromon and 6element to be on different machines. Whatever our choice is, let's be explicit about it.

**Comment by SergeBredin** [comment]
Just my opinion: I choose (definitely) the 2nd option, differentiate 6element and Pheromon with API calls must imply code, install and deployment partition (+ 6element-fork-argument)

**Comment by vallettea** [comment]
I'm also in favor of the current solution. Let's keep them cleanly separated.
