### ISSUE TITLE
Use localStorage instead of cookies

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#192]

**Comment by SergeBredin** [comment]
I am not comfortable with that. This week, we will add a credit page and mention cookies.

**Comment by DavidBruant** [comment]
Not sure what there is to be uncomfortable with. For a use case like saving favs, every resource on the web will tell to use localStorage instead of cookies. It's what I teach in training as well.
Browsers are being more and more aggressive at removing cookies because of tracking usages, cookies are unreliable to save favorites.

Examples : https://developer.mozilla.org/en-US/docs/Web/API/Storage#Examples

Until you have user accounts, you don't need cookies at all.
