### ISSUE TITLE
Add a cron job to query OSM daily

### ISSUE THREAD

**Issue by iOiurson** [anthill/6element#203]

**Comment by iOiurson** [comment]
We need not to forget about this.
Currently, the code to query OSM every day is not set as a CRON job. So we basically never update ou OSM points.
@vallettea, when you have a moment, we should address this.

**Comment by vallettea** [comment]
But I though it was done from the begining we have the following cron job on the server:

```
- name: Creates daily osm data loader
  cron: minute="00" hour="02"
        name="OSM_fetch"
        user="root"
        job="/bin/bash -c '. ~/.nvm/nvm.sh; cd /root/{{service_name}}; nvm use; node server/loadOSMtoDb.js'"
```

where can i check if the data is updated ?

**Comment by iOiurson** [comment]
Oops, i forgot you actually set up the CRON job... my bad, i should have closed the issue. We drop the osm_places in the process, so we can't use the timestamps to check if it's updated. But there are some console logs:

```
        console.log('Recycling points in OSM:', data.length);
        console.log('New points:', data.length - Object.keys(savedBins).length);
        console.log('Creating points in DB ...');
```

They should appear in the server logs.
