### ISSUE TITLE
Personas, Scenarios and User Test - Theory

### ISSUE THREAD

**Issue by RxnDbr** [anthill/6element#24]
# Personas

## Definition
The purpose of personas is to create reliable and realistic representations of key audience segments for reference. These representations should be based on qualitative and some quantitative user research and web analytics. 

They are not 'agents' or 'actors' in a script, they are people.

### Primary Persona
Primary persona is the main target of the product, from the most important group of users, the kind of person we must satisfy in priority.

### Secondary Persona
Secondary persona are less important. Their demand must be satisfied but not disturbing primary's

## Interest
* To think about users in action helps more efficiently to predict users behavior and reactions.
* To define the real need permit not to develop useless features
* To perceive targets as human being create empathy and involve more relevant apps
* To offer simpler and clearer apps
* To create a unique base in the work team
* To rationalize decisions
* To prioritize

## Persona form
They must answer these questions:
* **Who** will use my app?
* **What** is their goal?
* **How** will they do it?

## How to build personas?
In most cases, personas are synthesized from data collected from **interviews** with users. They are captured in **1–2-page** descriptions that include behavior patterns, goals, skills, attitudes, and the environment, with a few fictional personal details to make the persona a **realistic character**. Persona must be realistic, not extreme to make sense in duration (it is difficult to identify a caricature). For each product, more than one persona is usually created, but **one persona should always be the primary focus for the design**.
For any given project, creating **only three or four personas** is best. The goal of personas is not representing all audiences or addressing all needs of the website but instead to focus on the major needs of the most important user groups.

## Elements

* Persona Group (i.e. web manager)
* Fictional name
* Job titles and major responsibilities
* Demographics such as age, education, ethnicity, and family status
* The goals and tasks they are trying to complete using the site
* Their physical, social, and technological environment
* A quote that sums up what matters most to the persona as it relates to your site
* Casual pictures representing that user group

**Personas are useful not only to write scenarios, they are a source of information by themeselves** 

[Learn more...] (http://www.usability.gov/how-to-and-tools/methods/personas.html)

# Scenarios (Task-Based)
Scenarios will be used here to elaborate using tests. There are different kind of scenarios but we will focus on task-based scenarios.

## Definition
Scenarios are stories. They consist of a setting, or situation state, one or more actors with
personal motivations, knowledge, and capabilities, and various tools and objects that the
actors encounter and manipulate. **The scenario describes a sequence of actions and events
that lead to an outcome**. These actions and events are related in a **usage context** that
includes the goals, plans, and reactions of the people taking part in the episode.
Include in a user test, it lets users show you **how they would use the site to accomplish that goal**.
**Example to test employee's section on a company website/app** : You are traveling to Seattle for your job next week and you want to check on the amount you can be reimbursed for meals and other expenses.

## Interest
A good use scenario does a number of things:
* Describes the **user's goals**  and **motivations**.
* Describes a specific **task** or tasks that need to be accomplished.
* Describes some of the **interaction** with enough detail to make it compelling, but not so much detail as to be overwhelming.
* Provides a shared understanding for everyone on the work team about what a user might want to do and how they might do it.
* Helps construct the **sequence of events** that are necessary to address in user interface.
* Can be sketchy, as long as it provokes ideas and discussion. 

## Scenarios and personas
Scenarios can be constructed around personas, but the personas come first. To write an appropriate scenario with a personna, it is important to know : 
* What does the persona hope to accomplish by visiting the website,  
* What characteristics of the persona might help or hinder his or her site interaction?

Because we want to conceive using test, we won't include persona into the scenarios. They will permit to define targets in a first step so we can conceive using situations with scenarios.

## Scenarios form
They must answer these questions:
* **Who** is the user? Use the personas that have been developed to reflect the real, major user groups coming to your site.
* **Why** does the user come to the site?  Note what motivates the user to come to the site and their expectations upon arrival, if any.
* **What goals** does he/she have? Through task analysis, you can better understand the what the user wants on your site and therefore what the site must have for them to leave satisfied. 
Some scenarios also answer:
* **How can**  the user achieve their goals on the site? Define how the user can achieve his/ her goal on the site, identifying the various possibilities and any potential barriers.

## Elements
A task contains:
* Explanation of the issue 
* Explanation of the goal

Do not include any information on how the user would complete the scenario. 

When identifying scenarios for usability testing, limit your test to 10 to 12 tasks (due to time constraints). 

*Additionally, in a usability test, you can ask users for their own scenarios. Why would they come to your site? What do they want to do?*

## Scenarios and how to accomplish tasks
Usability testing scenarios should **not** include any information about how to accomplish a task. *But* it is important to write down how to accomplish the task. This information is included in the material that the observers and note-takers will use. Include the main pathway and any alternative pathways the participant may use to accomplish the scenario. 
After the test, compare how you thought users would complete the task to how they actually completed the task. This comparison provides valuable insight into the effectiveness of your site’s architecture and navigation

## 3 Golden rules
During a usability test, mimic the real world as much as possible. Recruit representative users and ensure that each task scenario
* Is realistic and typical for how people actually use the system, when they are on their own time, doing their own activities
* Encourages users to interact with the interface
* Doesn’t give away the answer

[Learn more about these rules] (http://www.nngroup.com/articles/task-scenarios-usability-testing/)

**We will use the previous scenarios to build the user tests**
[Learn more about scenarios] (http://www.usability.gov/how-to-and-tools/methods/scenarios.html)

# User test
User tests allow to watch how people use an application. It must be made with prototypes to ensure that the product is well designed for users.
It refers to evaluating a product or service by testing it with representative users. Typically, during a test, participants will try to complete typical tasks while observers watch, listen and takes notes.  
To run an effective usability test, steps are : 
* To develop a solid test plan
* To recruit participants 
* To analyze and report your findings

## Interest
Usability testing lets the design and development teams identify problems before they are coded. The earlier issues are identified and fixed, the less expensive the fixes will be in terms of both staff time and possible impact to the schedule.  During a usability test, you will:
* Learn if participants are able to complete specified tasks successfully and
* Identify how long it takes to complete specified tasks
* Find out how satisfied participants are with your Web site or other product
* Identify changes required to improve user performance and satisfaction
* And analyze the performance to see if it meets your usability objectives

## Test plan

Planning the test involves:
* **Scope**

Indicate what will be tested. Specify how much of the product the test will cover (e.g. the prototype as of a specific date; the navigation; navigation and content).
* **Purpose**

Identify concerns, questions, and goals for this test. In each round of testing, there will probably have several general and several specific concerns to focus on. Concerns should drive the scenarios to choose for the usability test.
* **Schedule & Location**

Indicate when and where the test will be done. If there is the schedule set,  be specific about how many sessions will hold in a day and exactly what times the sessions will be.
* **Sessions**

Describe the sessions, the length of the sessions (typically one hour to 90 minutes
* **Equipment**

Indicate the type of equipment you will be using in the test; desktop, laptop, mobile/Smartphone. Also indicate if you are planning on recording or audio taping the test sessions or using any special usability testing and/or accessibility tools.
* **Participants**

Indicate the number and types of participants to be tested you will be recruiting. Describe how these participants were or will be recruited and consider including the screener as part of the appendix.
* **Scenarios**

Indicate the number and types of tasks included in testing. Typically, for a 60 min. test, you should end up with approximately 8 (+/- 2) scenarios for a mobile/smartphone test. You may want to include more in the test plan so the team can choose the appropriate tasks.
* **Metrics**

  + Subjective metrics: Include the questions you are going to ask the participants prior to the sessions (e.g., background questionnaire), after each task scenario is completed (ease and satisfaction questions about the task), and overall ease, satisfaction and likelihood to use/recommend questions when the sessions is completed.
  + Quantitative metrics: Indicate the quantitative data you will be measuring in your test (e.g., successful completion rates, error rates, time on task).
* **Roles**

Include a list of the staff who will participate in the usability testing and what role each will play. The usability specialist should be the facilitator of the sessions. The usability team may also provide the primary note-taker. Other team members should be expected to participate as observers and, perhaps, as note-takers.

[Learn moreabout plan test] (http://www.usability.gov/how-to-and-tools/methods/planning-usability-testing.html)

## Recruit participant

It is vital to recruit participants who are similar to your site users for your usability testing.  Depending on the site or product, you may have multiple potential users groups.  Try to include representatives of all these groups or optimally.

Internal staff may be used for pilot testing since you are testing the technology and the flow of the test and the data is not factored into the final results. Internal staff should never be used to supplement during testing. 

*How many participants are enough?*

Nielsen outlines the number of participants External Link Disclosure that you need.Usability Tests  needs only 5 users to find almost as many usability problems as you'd find using many more test participants.

[Learn more about recruitment] (http://www.nngroup.com/articles/recruiting-test-participants-for-usability-studies/)

## Analyse and report
When analyzing the data taht have been collected, it is important to read through the notes carefully looking for patterns and be sure to add a description of each of the problems. Looks for trends and keep a count of problems that occurred across participants.

### Quantitative data
Data must be recorded in a spreadsheet that include:
* Success rates,
* Task time,
* Error rates,
* Satisfaction questionnaire ratings
Do not forget to specify scenarios tasks for each metrics

### Qualitative data
Data concern:
* Observations about pathways participants took
* Problems experienced
* Comments/recommendations
* Answers to open-ended questions

Problems statements must be exact and concise but detailed. For instance : Did that instead do this.

## Severity of the problems
To help differentiate, we should note the severity of the problems on a 3/4-point scale. 
For example:
* **Critical** :  If we do not fix this, users will not be able to complete the scenario.
* **Serious** :  Many users will be frustrated if we do not fix this; they may give up.
* **Minor** :  Users are annoyed, but this does not keep them from completing the scenario. This should be revisited later.

## Report
To know how to write the report, refers [usability](www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)

# Conclusion
Now we've learned about personas, scenarios and using test theory, we can think more practically about the app. To be sure the app we develop is well designed and adapted to the users we first have to know **who** are they. Personas are a powerful tool to represent them. The next step is defining in which context our app will be used. That what the scenarios are usef for. Then, development can start. When the prototypes will be done, using tests will be made to ensure the app is used in the way we thought. Usings tests have to be made after each improvement and helps actually to improve.

Now we know how an app should be designed, we can start practice !

**Comment by vallettea** [comment]
:+1: 
- be careful not to copy paste too much paragraphs that are going into too much details. Keep in mind that we should just have to glance at you note to see the main points (use **bold writing**) and give references in the text for more details.
- you should conclude with a call to action: from what we just learned what should we do know.

**Comment by DavidBruant** [comment]
Example of Personas https://speakerdeck.com/mariealine/et-toi-cest-quoi-tes-ux-tips?slide=9

**Comment by vallettea** [comment]
This is excellent ! :+1:
