### ISSUE TITLE
App React multiples

### ISSUE THREAD

**Issue by iOiurson** [anthill/6element#34]
*Sorry folks, i already wrote this in french before posting it here*

@DavidBruant, je suis en train de commencer une page d’admin pour nos capteurs, et du coup je réfléchissais à la structure du dossier.

En fait, ca serait une page différente de notre liveMap avec les points, donc théoriquement une app différente. Mais ca reste côté client.
Ma question est donc, comment structurer plusieurs app React au sein d’un même projet ?

Ma structure doit-elle être:

/client
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/app1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/app2

avec chacun son /css, son /src, son index.html, son main.js et par conséquent son app.js généré par browserify/watchify

ou alors quelque chose dans le genre:

/client
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/css
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app1.css
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app2.css
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/src
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/Components
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main1.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main2.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index1.html
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index2.html
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app1.js
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app2.js

Je trouve la solution 1 plus claire, mais la solution permet de mieux capitaliser sur des morceaux de code commun (je sais pas trop si j’en aurai beaucoup sur ce cas particulier, mais ma question est générale).
 
En l’écrivant comme ca, je trouve que la solution 2 est quand meme assez naze, mais j’aimerais ton avis.

**Comment by DavidBruant** [comment]
Yep, large preference for the first solution.
If things are shared across, let's create a `shared` directory or else.

**Comment by iOiurson** [comment]
Closing
