### ISSUE TITLE
Fix socket.io one-client bug

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#52]
https://github.com/anthill/6element/blob/63c1e639220fa48715f71e386ea143343656ccd2/app/server/index.js#L53-L57
(and the rest of the code only uses the `socket` variable)

This makes that only the last client to connect to the server receives push updates.
Instead, need to create a `Set`, then do `.add` and `.delete` on 'connection' and 'disconnect' events. When a SMS comes in (or other event), do a `.emit` on every socket in the set. (`sockets.forEach`, etc.)

**Comment by 4rzael** [comment]
The easiest way to do this is using [io.sockets.emit()](https://github.com/socketio/socket.io#serveremit)
I'm fixing this problem.

**Comment by 4rzael** [comment]
Fixed by #77
