### ISSUE TITLE
Separate app and the part receiving sensor measurements

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#55]
Follow up to #37. App and the part receiving the measurements couldn't be separated, because the sensors deployed today expect to send to `6element.ants.builders/twilio`, so the two parts have to be bundled together.
When we make a definitive choice to how the info is sent to the server, let's separate them (remember they'll need to talk via TCP so events can be pushed to the clients via socket.io)

**Comment by 4rzael** [comment]
## Fixed in #76

Now that sensors use tcp (and not sms), this problem is fixed. The reception server (endpoint) receive data, decode it, store it, and send it to the app, which only handle web clients.
