### ISSUE TITLE
Maybe find an alternative to Travis

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#59]
Travis doesn't seem to be compatible with Docker-contained apps. http://stackoverflow.com/a/26100325
There exists solutions apparently, but they seem to be to much work to be workable for now https://github.com/jpetazzo/sekexe (or via binary https://docs.docker.com/installation/binaries/ and sudo: false according to @oncletom )

Postgres http://docs.travis-ci.com/user/using-postgresql/

**Comment by oncletom** [comment]
https://circleci.com/integrations/docker

**Comment by vallettea** [comment]
circleci looks good but it is quite expensive...

**Comment by oncletom** [comment]
Compare to how much of your time it costs and see if it worth it. Otherwise ask them to be a sponsor of the project :-)
