### ISSUE TITLE
Finish App/Admin separation

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6element#61]
In #37, we separated the server sides of app and admin.
On the other end, the client are already separated in different folders.

We should go all the way and end up with something like
````
node/
    common/
        database/
        ...
    app/
        client/
        server/
        ...
    server/ 
        client/
        server/
        ...
    sensorsServer/ # eventually    
        ...
...
````

**Comment by iOiurson** [comment]
I believe this was addressed by #62, even if we don't this exact structure. Should we close or wait until we create the receptionServer to close definitively this issue ??
